name: Claude Auto Review & PR

on:
  push:
    branches:
      - 'feature/**'
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  create_pr:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Pull Request
        run: |
          gh pr create \
            --title "Auto PR: ${{ github.ref_name }}" \
            --body "Automated PR from ${{ github.ref_name }}. Claude will review and add tests." \
            --base main \
            --head ${{ github.ref_name }} || echo "PR already exists"
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}

  claude_review:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run Claude Code Action to review & add tests
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.PAT_TOKEN }}
          prompt: |
            You are an automated senior code reviewer and test writer.

            IMPORTANT INSTRUCTIONS:
            1. Review all changed files in this PR compared to main branch.
            2. Identify what the code is supposed to do and check if tests match the implementation.
            3. Add **new Jest test cases** for new functionality or missing edge cases (NEVER modify or delete existing tests).
            4. If tests are failing, either fix the code OR add new tests that match the new behavior.
            5. Run `npm test` to verify all tests pass.
            6. Run `npm run lint` (or eslint --fix if available) to fix style issues.
            7. You MUST commit all changes with: git add -A && git commit -m "chore(claude): added tests and fixes" && git push

            Follow the guidelines in CLAUDE.md file.
